// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_ZBWZrKkWn8Bw8tLaXm50yYLCcc8xxKs',
    appId: '1:953138134771:android:12fa8c48bd3e72d7f30186',
    messagingSenderId: '953138134771',
    projectId: 'guardiao-jus',
    storageBucket: 'guardiao-jus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZ0I0Hc5VgGo5OgxiOJwVRXV8g4CODMk',
    appId: '1:953138134771:ios:a505169c16680d26f30186',
    messagingSenderId: '953138134771',
    projectId: 'guardiao-jus',
    storageBucket: 'guardiao-jus.firebasestorage.app',
    androidClientId: '953138134771-d982uj29mvc429aans64va21iga5omdn.apps.googleusercontent.com',
    iosClientId: '953138134771-8cf7u4dpbddq6b5bnteiv2lpmuo3gd4a.apps.googleusercontent.com',
    iosBundleId: 'com.selddon.guardiao.cliente',
  );

}